#ROUTE ACCEUIL
homepage:
    path:     /
    defaults: { _controller: ATCAppBundle:Default:index }

#ROUTE POUR LE QUESTIONNAIRE 
questionnaire_difficulte:
    path: /questionnaire
    defaults: { _controller: ATCAppBundle:Questionnaire:indexDifficulte }

questionnaire_theme:
    path: /questionnaire/{difficulte}
    defaults: { _controller: ATCAppBundle:Questionnaire:indexTheme }

questionnaire:
    path: /questionnaire/{difficulte}/{theme}/{id}/{numero_question}.{score}
    defaults: { _controller: ATCAppBundle:Questionnaire:view }


#ROUTE ADMINISTRATEUR
administrateur:
    path: /administrateur
    defaults: {_controller: ATCAppBundle:Administrateur:index}

administrateur_ajout_questionnaire:
    path: /administrateur/ajout_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:add}

administrateur_complete_questionnaire:
    path: /administrateur/complete_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:complete}

#ROUTE QUESTION
question_ajout:
    path: /administrateur/ajout_questionnaire/ajout_question/{titre}
    defaults: {_controller: ATCAppBundle:Question:add}

#ROUTE CLASSEMENT
classement:
    path: /classement   
    defaults: {_controller: ATCAppBundle:Classement:index}

#ROUTE CHRONO
chrono:
    path: /chrono
    defaults: {_controller: ATCAppBundle:Questionnaire:chrono}