#ROUTE ACCEUIL
homepage:
    path:     /
    defaults: { _controller: ATCAppBundle:Default:index }

#ROUTE POUR LE QUESTIONNAIRE
questionnaire_theme:
    path: /questionnaire
    defaults: { _controller: ATCAppBundle:Theme:index}

questionnaire_difficulte:
    path: /questionnaire/{theme}
    defaults: { _controller: ATCAppBundle:Difficulte:index}

questionnaire:
    path: /questionnaire/{theme}/{difficulte}/{numero_question}.{score}
    defaults: { _controller: ATCAppBundle:Questionnaire:view }

score:
    path: /score/{nom_questionnaire}.{theme_questionnaire}.{difficulte_questionnaire}.{score}
    defaults: { _controller: ATCAppBundle:Questionnaire:score}

joueur_add:
    path: /score_add
    defaults: { _controller: ATCAppBundle:Joueur:add}


#ROUTE ADMINISTRATEUR
administrateur:
    path: /administrateur
    defaults: {_controller: ATCAppBundle:Administrateur:index}

administrateur_ajout_questionnaire:
    path: /administrateur/ajout_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:add}

administrateur_complete_questionnaire:
    path: /administrateur/complete_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:completeView}

administrateur_delete:
    path: /administrateur/verif_questionnaire
    defaults: {_controller: ATCAppBundle:Administrateur:delete}

#ROUTE QUESTION
question_ajout:
    path: /administrateur/ajout_questionnaire/ajout_question/{titre}
    defaults: {_controller: ATCAppBundle:Question:add}

question_show:
     path: /show
     defaults: {_controller: ATCAppBundle:Question:show}

question_update:
    path: /update
    defaults: {_controller: ATCAppBundle:Question:update}

#ROUTE CLASSEMENT
classement:
    path: /classement   
    defaults: {_controller: ATCAppBundle:Classement:index}

#ROUTE CHRONO
chrono:
    path: /chrono
    defaults: {_controller: ATCAppBundle:Questionnaire:chrono}

#LOGIN
login_show:
    path: /login_show
    defaults: {_controller: ATCAppBundle:Security:show}
    
login:
    path: /login
    defaults: {_controller: ATCAppBundle:Security:login}