#ROUTE ACCEUIL
homepage:
    path:     /
    defaults: { _controller: ATCAppBundle:Default:index }

#ROUTE POUR LE QUESTIONNAIRE
questionnaire_theme:
    path: /questionnaire
    defaults: { _controller: ATCAppBundle:Theme:index}

questionnaire_difficulte:
    path: /questionnaire/{theme}
    defaults: { _controller: ATCAppBundle:Difficulte:index}

questionnaire:
    path: /questionnaire/{theme}/{difficulte}/{numero_question}.{score}
    defaults: { _controller: ATCAppBundle:Questionnaire:view }

score:
    path: /score/{nom_questionnaire}.{theme_questionnaire}.{difficulte_questionnaire}.{score}
    defaults: { _controller: ATCAppBundle:Questionnaire:score}

joueur_add:
    path: /score_add
    defaults: { _controller: ATCAppBundle:Joueur:add}


#ROUTE ADMINISTRATEUR
administrateur:
    path: /administrateur
    defaults: {_controller: ATCAppBundle:Administrateur:index}

administrateur_ajout_questionnaire:
    path: /administrateur/ajout_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:add}

administrateur_complete_questionnaire:
    path: /administrateur/complete_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:completeView}

#ROUTE QUESTION
question_ajout:
    path: /administrateur/ajout_questionnaire/ajout_question/{titre}
    defaults: {_controller: ATCAppBundle:Question:add}

#ROUTE CLASSEMENT
classement:
    path: /classement   
    defaults: {_controller: ATCAppBundle:Classement:index}

#ROUTE CHRONO
chrono:
    path: /chrono
    defaults: {_controller: ATCAppBundle:Questionnaire:chrono}