#ROUTE ACCEUIL
homepage:
    path:     /
    defaults: { _controller: ATCAppBundle:Default:index }

#ROUTE POUR LE QUESTIONNAIRE 
questionnaire:
    path: /questionnaire
    defaults: { _controller: ATCAppBundle:Questionnaire:index }

questionnaire_facile:
    path: /questionnaire/facile
    defaults: { _controller: ATCAppBundle:Questionnaire:facile }

questionnaire_moyen:
    path: /questionnaire/moyen
    defaults: { _controller: ATCAppBundle:Questionnaire:moyen }

questionnaire_difficile:
    path: /questionnaire/difficile
    defaults: { _controller: ATCAppBundle:Questionnaire:difficile }

#AFFICHAGE DES QUESTION
questionnaire_facile_math:
    path: /questionnaire/facile/math{id}
    defaults: {_controller: ATCAppBundle:Questionnaire:view }


#ROUTE ADMINISTRATEUR
administrateur:
    path: /administrateur
    defaults: {_controller: ATCAppBundle:Administrateur:index}

administrateur_ajout_questionnaire:
    path: /administrateur/ajout_questionnaire
    defaults: {_controller: ATCAppBundle:Questionnaire:add}

administrateur_ajout_questionnaire2:                              # Chemin lien entre pages du site  
    path: /administrateur/ajout_questionnaire2
    defaults: {_controller: ATCAppBundle:Question:add}


#ROUTE QUESTION
question_ajout:
    path: /administrateur/ajout_questionnaire/ajout_question
    defaults: {_controller: ATCAppBundle:Question:add}

#ROUTE CLASSEMENT
classement:
    path: /classement   
    defaults: {_controller: ATCAppBundle:Classement:index}