<?php

namespace ATC\AppBundle\Repository;

/**
 * DifficulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DifficulteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByNom($nom)
    {
        $query = $this->_em->createQuery('SELECT d
        FROM ATCAppBundle:Difficulte d
        WHERE d.nom = :nom ');
        
        $query->setParameter('nom', $nom);
        
        return  $query->getResult();
    }
}
