<?php

namespace ATC\AppBundle\Repository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
      public function findAllQuestionnaireByUncompletede()
    {
    
        $sql = "SELECT COUNT(q), q.id, q.titre, t.nom as theme , d.nom as difficulte
        FROM ATCAppBundle:Contenu c
        JOIN ATCAppBundle:Questionnaire q WHERE q.id = c.questionnaire
        JOIN ATCAppBundle:Themes t WHERE q.theme = t.id
        JOIN ATCAppBundle:Difficulte d WHERE q.difficulte = d
        GROUP BY c.questionnaire";

        $query = $this->_em->createQuery($sql);

        return $query->getResult();
    }

    
}
