<?php

namespace ATC\AppBundle\Repository;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Console\Question\Question;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuestionByQuestionnaire($questionnaire)
    {       
            $query = $this->_em->createQuery('SELECT q
            FROM ATCAppBundle:Question q
            JOIN ATCAppBundle:Contenu c WHERE q.id = c.idQuestion
            JOIN ATCAppBundle:Questionnaire qs WHERE qs.id = c.idQuestionnaire
            WHERE qs.id = :id AND qs.theme = :theme AND qs.difficulte = :difficulte');
            
            $query->setParameter('id', $questionnaire->getId());
            $query->setParameter('theme',$questionnaire->getTheme()->getId());
            $query->setParameter('difficulte', $questionnaire->getDifficulte()->getId());
        
            $questions =   $query->getResult();

            return $questions;
       
    }

    /**
     * @param int
     * 
     * return le nombre de question du questionnaire
     * @return int 
     */
    public function countQuestionByQuestionnaire($id)
    {
            $query = $this->_em->createQuery('SELECT COUNT(c) 
            FROM ATCAppBundle:Contenu c
            WHERE c.idQuestionnaire = :id');
            
            $query->setParameter('id', $id);
            
            return  (int) $query->getSingleScalarResult();
        
    }

}
