<?php

namespace ATC\AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuestionByQuestionnaire($id,$theme,$difficulte)
    {       
            $query = $this->_em->createQuery('SELECT q
            FROM ATCAppBundle:Question q
            JOIN ATCAppBundle:Contenu c WHERE q.id = c.idQuestion
            JOIN ATCAppBundle:Questionnaire qs WHERE qs.id = c.idQuestionnaire
            WHERE qs.id = :id AND qs.theme = :theme AND qs.difficulte = :difficulte');
            
            $query->setParameter('id', $id);
            $query->setParameter('theme', $theme);
            $query->setParameter('difficulte', $difficulte);
            
            return  $query->getResult();
       
    }

    public function countQuestionByQuestionnaire($id)
    {
            $query = $this->_em->createQuery('SELECT COUNT(c) AS nbrQuestionn 
            FROM contenu c
            WHERE c.idQuestionnaire = :id');
            
            $query->setParameter('id', $id);
            
            return  $query->getResult();
    }
}
