<?php

namespace ATC\AppBundle\Repository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneRandQuestionnaireByTheme($theme,$difficulte)
    {
            $query = $this->_em->createQuery('SELECT q 
            FROM ATCAppBundle:Questionnaire q
            JOIN ATCAppBundle:Themes t WHERE q.id_theme = t.id
            JOIN ATCAppBundle:Difficulte d WHERE q.id_difficulte = d.id
            WHERE t.nom = :theme AND d.nom = :difficulte
            ORDER BY RAND() LIMIT 1');
            
            $query->setParameter('theme', $theme);
            $query->setParameter('difficulte', $difficulte);

            return  $query->getResult();
    }

    public function findAllQuestionnaireByUncompletede()
    {
        $sql = "SELECT COUNT(q), q.id, q.titre, t.nom as theme , d.nom as difficulte
        FROM ATCAppBundle:Contenu c
        JOIN ATCAppBundle:Questionnaire q WHERE q.id = c.idQuestionnaire
        JOIN ATCAppBundle:Themes t WHERE q.id_theme = t.id
        JOIN ATCAppBundle:Difficulte d WHERE q.id_difficulte = d.id
        GROUP BY c.idQuestionnaire";

        $query = $this->_em->createQuery($sql);

        return $query->getResult();
    }
}
